### ISSUE TITLE
Числата в крайната таблица не излизат след точката.

### ISSUE THREAD

**Issue by Neychok** [Neychok/finance-calculator#1]
Проверих и не се закръглят числата, а всъщност просто не се показват самите цифри.
Предполагам проблема е в начина на изобразяване на числата.

Към Мони: Пробвай да изобразиш таблицата по друг начин, ако не намериш някакво решение.

**Comment by Megas97** [comment]
Пробвай тези 2 начина: 
За C#: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?fbclid=IwAR1psHS9YFNjbxoQI3u8ygVQYtIcMr2DCTkxXdnfqT-ua76Uskd5GSgfO48#the-currency-c-format-specifier
За JS: https://stackoverflow.com/questions/149055/how-can-i-format-numbers-as-dollars-currency-string-in-javascript?fbclid=IwAR2HHH9f30dlMXmd7hRkUEax0bNbneTY5VX-4d0EQd3QM6hyVXChYyJJgJw

**Comment by Neychok** [comment]
Оправи се. Смених крайните стойности на Decimal и ги закръглих, и се получи.
