### ISSUE TITLE
ГПР Формулата

### ISSUE THREAD

**Issue by Neychok** [Neychok/finance-calculator#2]
Не можах да намеря формули за някои от сметките.
Формулата, която намерих за ГПР (Годишен процентен разход) работи само в някои от случаите и не е особено точна.
Месечните и годишните такси (процент) са неточни. Те се изчисляват като процент от Вносната главница (Месечната вноска без лихвата). Тъй като не мога да намеря каква трябва да е лихвата за всеки месец (зная само средната на месец), не мога да намеря каква е Вносната главница и не мога да изчисля въпросните такси.
Сега използвам месечната вноска вместо вносната главница.

**Comment by Neychok** [comment]
Оправих всички формули и вече смятат правилно, освен ГПР формулата, която все още не мога да намеря.

**Comment by Megas97** [comment]
Това може би? https://forum.investor.bg/forum/алтернативни-инвестиции/дългов-пазар/6750-има-ли-формула-за-смятане-на-гпр
Третият пост^.

**Comment by Neychok** [comment]
Точно тази формула смятам. ама тя не взима в предвид таксите и промоционалните периоди.

**Comment by Megas97** [comment]
Тук пише нещо за таксите: https://www.forumfinansi.com/threads/Как-да-калкулираме-ГПР-то-или-годишният-процент-на-разходите.115/
