### ISSUE TITLE
Да се извеждат числата в по-добър формат

### ISSUE THREAD

**Issue by Neychok** [Neychok/finance-calculator#4]
Знам, че е нещо дребно, но ще изглежда доста по-добре.
Примерно числото " 123456.78" в таблицата излиза като " 123456.78 BGN" и ще е по-добре, ако се направи да излиза като " 123 456.78 лв"
Пробвах с .ToString и би трябвало да ги превръща числата в string с правилния формат, обаче като се опитам да ги изкарам в таблицата и тя спира да работи изцяло, въобще не се появява.

**Comment by Megas97** [comment]
Знам как става в Lua: http://lua-users.org/wiki/FormattingNumbers
За C# май само с .ToString може: https://stackoverflow.com/questions/30042623/adding-commas-to-integers-in-c-sharp
Всъщност ето и малко по друг начин с Format: https://stackoverflow.com/questions/13195648/string-format-c-sharp-spacing-between-every-1000-number

**Comment by Neychok** [comment]
Не, то аз знам как да го направя, въпроса е, че таблицата не иска да изкара string-a.

**Comment by Megas97** [comment]
Ето го и решението - форматираме числата чрез JavaScript, а не C#: https://stackoverflow.com/questions/9743038/how-do-i-add-a-thousand-seperator-to-a-number-in-javascript?fbclid=IwAR2fJxSj-aQZU_EgDgLR2uXXo_nbBzRD4kqDvEj4yVewAaWqqdvSBDlKpfE
